# Generated by Django 3.2.4 on 2021-06-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0002_alter_notificacion_destinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='nivel',
            field=models.CharField(choices=[('Exito', 'exito'), ('Informacion', 'informacion'), ('Advertencia', 'advertencia'), ('Error', 'error'), ('Direccion', 'direccion')], default='Informacion', max_length=20),
        ),
    ]
