# Generated by Django 3.2.4 on 2021-06-21 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='relacionados',
            field=models.ManyToManyField(blank=True, related_name='_Dashboard_producto_relacionados_+', through='Dashboard.ProductoRelacionado', to='Dashboard.producto'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epayco_charge_id', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
