# Generated by Django 3.2.4 on 2021-06-11 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_rename_ordenarpedido_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='producto',
            new_name='productos',
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(default='Aguachica', max_length=50)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('kind_address', models.CharField(choices=[('CARRERA', 'Carr'), ('CALLE', 'Calle'), ('AVENIDA', 'Avenida')], max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('hastag', models.CharField(default='#', max_length=1)),
                ('numero1', models.CharField(max_length=2)),
                ('numero2', models.CharField(blank=True, max_length=2, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
