# Generated by Django 3.2.4 on 2021-06-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20210611_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Descuento'),
        ),
    ]
