# Generated by Django 3.2.4 on 2021-06-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20210614_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.direccion'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='Dashboard.usuario'),
            preserve_default=False,
        ),
    ]
