# Generated by Django 3.2.4 on 2021-06-11 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=60, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ciudad_data', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=120, null=True)),
                ('pais', models.CharField(blank=True, max_length=120, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
